version: '3'

services:
  mongodb:
    image: 'mongo'
    ports:
      - 27017:27017
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

    volumes:
      - ./data:/data/db
    networks:
      - shared-net
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    networks:
      - shared-net
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - '8090:8081'
    restart: always
    volumes:
      - ./data:/data/db

  app:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - shared-net
networks:
  shared-net:
    driver: bridge